//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ServiceModel;


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="_2_IContrato")]
public interface _2_IContrato
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/_2_IContrato/ObtenerMensaje", ReplyAction="http://tempuri.org/_2_IContrato/ObtenerMensajeResponse")]
    string ObtenerMensaje(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/_2_IContrato/ObtenerMensaje", ReplyAction="http://tempuri.org/_2_IContrato/ObtenerMensajeResponse")]
    System.Threading.Tasks.Task<string> ObtenerMensajeAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface _2_IContratoChannel : _2_IContrato, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class _2_IContratoClient : System.ServiceModel.ClientBase<_2_IContrato>, _2_IContrato
{
    
    public _2_IContratoClient()
    {
    }
    
    public _2_IContratoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public _2_IContratoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public _2_IContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public _2_IContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ObtenerMensaje(string name)
    {
        return base.Channel.ObtenerMensaje(name);
    }
    
    public System.Threading.Tasks.Task<string> ObtenerMensajeAsync(string name)
    {
        return base.Channel.ObtenerMensajeAsync(name);
    }
}
